src/Bibliometry/MainBundle/Entity/Conference.php
<?php

namespace Bibliometry\MainBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * Conference
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="Bibliometry\MainBundle\Entity\ConferenceRepository")
 */
class Conference
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=255)
     */
    private $title;
    
    /**
     * @Gedmo\Slug(fields={"title"})
     * @ORM\Column(length=128, unique=true)
     */
    private $slug;
    
     /**
     * @var string
     *
     * @ORM\Column(name="preProcessedTitle", type="string", length=255)
     */
    private $preProcessedTitle;

    /**
     * @var string
     *
     * @ORM\Column(name="acronym", type="string", length=255, nullable=true)
     */
    private $acronym;
    
    /**
    * @ORM\OneToMany(targetEntity="Bibliometry\MainBundle\Entity\PubliConference", mappedBy="conference")
    */
    private $publiConferences;
    
    /**
    * @ORM\OneToMany(targetEntity="Bibliometry\MainBundle\Entity\ConferenceRanking", mappedBy="conference", cascade = {"persist"})
    */
    private $conferenceRankings;

    public function __toString()
    {
        return $this->title;
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     * @return Conference
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string 
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set acronym
     *
     * @param string $acronym
     * @return Conference
     */
    public function setAcronym($acronym)
    {
        $this->acronym = $acronym;

        return $this;
    }

    /**
     * Get acronym
     *
     * @return string 
     */
    public function getAcronym()
    {
        return $this->acronym;
    }
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->publiConferences = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Add publiConferences
     *
     * @param \Bibliometry\MainBundle\Entity\PubliConference $publiConferences
     * @return Conference
     */
    public function addPubliConference(\Bibliometry\MainBundle\Entity\PubliConference $publiConferences)
    {
        $this->publiConferences[] = $publiConferences;

        return $this;
    }

    /**
     * Remove publiConferences
     *
     * @param \Bibliometry\MainBundle\Entity\PubliConference $publiConferences
     */
    public function removePubliConference(\Bibliometry\MainBundle\Entity\PubliConference $publiConferences)
    {
        $this->publiConferences->removeElement($publiConferences);
    }

    /**
     * Get publiConferences
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getPubliConferences()
    {
        return $this->publiConferences;
    }
    
    /**
     * Get Number of publication in this conference
     */
    public function getNbPubli()
    {
        $nb = 0;
        foreach($this->publiConferences as $publiConference)
            if ($publiConference->getPublication())
                $nb += 1;
        return $nb;
    }
    
    public function getEditions()
    {
        $toReturn = array();
        $seenYears = array();
        foreach ($this->getPubliConferences() as $publiConference)
        {
            if (!in_array($publiConference->getYear(), $seenYears))
            {
                $toReturn[] = $publiConference;
                $seenYears[] = $publiConference->getYear();
            }
        }
        usort($toReturn, array('\Bibliometry\MainBundle\Entity\Conference', 'compareEditions'));
        return $toReturn;
    }
    
    private static function compareEditions($edition1, $edition2)
    {
        if ($edition1->getYear() > $edition2->getYear())
        {
            return -1;
        }
        else if ($edition1->getYear() < $edition2->getYear())
        {
            return 1;
        }
        else 
        {
            return 0;
        }
    }

    /**
     * Add conferenceRankings
     *
     * @param \Bibliometry\MainBundle\Entity\ConferenceRanking $conferenceRanking
     * @return Conference
     */
    public function addConferenceRanking(\Bibliometry\MainBundle\Entity\ConferenceRanking $conferenceRanking)
    {
        $this->conferenceRankings[] = $conferenceRanking;
        $conferenceRanking->setConference($this);
        return $this;
    }

    /**
     * Remove conferenceRankings
     *
     * @param \Bibliometry\MainBundle\Entity\ConferenceRanking $conferenceRanking
     */
    public function removeConferenceRanking(\Bibliometry\MainBundle\Entity\ConferenceRanking $conferenceRanking)
    {
        $this->conferenceRankings->removeElement($conferenceRanking);
    }

    /**
     * Get conferenceRankings
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getConferenceRankings()
    {
        return $this->conferenceRankings;
    }
    
    /**
     * Get lastConferenceRanking
     *
     * @return \Bibliometry\MainBundle\Entity\ConferenceRanking 
     */
    public function getLastConferenceRanking($limitYear = 9999)
    {
        $maxYear = 0;
        $lastRanking = NULL;
        foreach ($this->getConferenceRankings() as $ranking)
        {
            if ($ranking->getYear() > $maxYear && $ranking->getYear() <= $limitYear)
            {
                $maxYear = $ranking->getYear();
                $lastRanking = $ranking;
            }
        }
        
        return $lastRanking;
    }
    
    /**
     * Get ConferenceRanking of a year
     *
     * @return \Bibliometry\MainBundle\Entity\ConferenceRanking 
     */
    public function getConferenceRankingYear($year)
    {
        foreach ($this->getConferenceRankings() as $ranking)
        {
            if ($ranking->getYear() == $year)
            {
                return $ranking;
            }
        }
        // If not found for this year, return last
        return $this->getLastConferenceRanking($year);
    }
    
    public function getConferenceRankingLabel()
    {
        $ranking = $this->getLastConferenceRanking();
        
        // No ranking
        if ($ranking == NULL)
        {
            // Check if conference is FR
            $publiConferences = $this->getPubliConferences();
            $languages = [ "fr" => 0, "other" => 0 ];
            foreach ($publiConferences as $publiConference)
            {
                if ($publiConference->getPublication()->getLanguage() == "fr")
                {
                    $languages["fr"]++;
                }
                else
                {
                    $languages["other"]++;
                }
            }
            if ($languages["fr"] > $languages["other"])
            {
                return "FR";
            }
            else
            {
                return "NC";
            }
        }
        // Return ranking
        else
        {
            return $ranking->getValue();
        }
    }
    
    public function getCoreLink()
    {
        if ($this->getLastConferenceRanking() != NULL)
        {
            return "http://portal.core.edu.au/conf-ranks/?search=".$this->getTitle()."&by=all&source=all&sort=atitle&page=1";
        }
        else {
            return NULL;
        }
    }

    /**
     * Set preProcessedTitle
     *
     * @param string $preProcessedTitle
     * @return Conference
     */
    public function setPreProcessedTitle($preProcessedTitle)
    {
        $this->preProcessedTitle = $preProcessedTitle;

        return $this;
    }

    /**
     * Get preProcessedTitle
     *
     * @return string 
     */
    public function getPreProcessedTitle()
    {
        return $this->preProcessedTitle;
    }

    /**
     * Set slug
     *
     * @param string $slug
     * @return Conference
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * Get slug
     *
     * @return string 
     */
    public function getSlug()
    {
        return $this->slug;
    }

    public function getPublications()
    {
        $toReturn = array();
        foreach ($this->getPubliConferences() as $publiConference)
        {
            $toReturn[] = $publiConference->getPublication();
        }
        return $toReturn;
    }
}

src/Bibliometry/MainBundle/Form/ConferenceType.php
<?php

namespace Bibliometry\MainBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ConferenceType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
            ->add('acronym')
        ;
    }
    
    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Bibliometry\MainBundle\Entity\Conference'
        ));
    }

    /**
     * @return string
     */
    public function getBlockPrefix()
    {
        return 'bibliometry_mainbundle_conference';
    }
}

src/Bibliometry/MainBundle/Controller/ConferenceController.php
<?php

namespace Bibliometry\MainBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use Bibliometry\MainBundle\Form\ConferenceType;
use Symfony\Component\HttpFoundation\Request;

class ConferenceController extends Controller
{

    /**
     * @Route("/conference", name="all_conferences_route")
     * @Template()
     */
    public function showConferencesAction()
    {
        $conferencesRepository = $this->getDoctrine()->getRepository('BibliometryMainBundle:Conference');
        $conferences = $conferencesRepository->getNotEmptyConferences();
        
        return array(
                'conferences' => $conferences
        );
    }

    /**
     * @Route("/conference/{slug_conference}", name="conference_route")
     * @Template()
     */
    public function showConferenceAction($slug_conference)
    {
        $conferencesRepository = $this->getDoctrine()->getRepository('BibliometryMainBundle:Conference');
        $conference = $conferencesRepository->findOneBySlug($slug_conference);
        
        // If not found, 404
        if($conference == NULL)
        {
            throw $this->createNotFoundException('This conference was not found on the website.');
        }
        
        return array(
                'conference' => $conference,
                'hasRightToSee' => $this->getUser()->hasRole('ROLE_ADMIN')
        );
    }

    /**
     * @Route("/edit-conference/{slug_conference}", name="edit_conference_route")
     * @Template()
     */
    public function editConferenceAction(Request $request, $slug_conference)
    {
        $conferencesRepository = $this->getDoctrine()->getRepository('BibliometryMainBundle:Conference');
        $conference = $conferencesRepository->findOneBySlug($slug_conference);
        
        // If not found, 404
        if($conference == NULL)
        {
            throw $this->createNotFoundException('This conference was not found on the website.');
        }
        
        if(false === $this->get('security.authorization_checker')->isGranted('ROLE_ADMIN'))
        {
            throw new AccessDeniedException();
        }
        
        $form = $this->createForm('Bibliometry\MainBundle\Form\ConferenceType', $conference);
        
        $form->handleRequest($request);
        
        if($form->isValid())
        {
            $em = $this->getDoctrine()->getManager();
            $em->persist($conference);
            $em->flush();
            
            $session = $request->getSession();
            $session->getFlashBag()->add('success', 'bibliometry.conference.edit_success');
            
            return $this->redirect($this->generateUrl('conference_route', array(
                    'slug_conference' => $conference->getSlug()
            )));
        }
        
        return array(
                'conference' => $conference,
                'form' => $form->createView()
        );
    }
}

src/Bibliometry/MainBundle/Resources/views/Conference/editConference.html.twig
{% block edit_conference %}
<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" id="edit_conference_popup">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">{{ 'bibliometry.conference.edit_conference_popup_title'|trans }}</h4>
            </div>
            {{ form_start(form, {'action': path('edit_conference_route', {'slug_conference': conference.slug})}) }}
                <div class="modal-body">
                    {{ form_row(form.title) }}
                    {{ form_row(form.acronym) }}
                    {{ form_rest(form) }}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">{{ 'bibliometry.errors.error_report.close'|trans }}</button>
                    <button type="submit" class="btn btn-primary">{{ 'bibliometry.conference.edit_conference_popup_submit'|trans }}</button>
                </div>
            {{ form_end(form) }}
        </div>
    </div>
</div>
{% endblock %}

src/Bibliometry/MainBundle/Resources/views/Conference/showConference.html.twig
{% extends "::base.html.twig" %}

{% block title %}{{ parent() }} - {{ conference.title }}{% endblock %}

{% block page_title %}
    <div style="width:60%;">{{ conference.acronym ? '['~conference.acronym~'] ':'' }}{{ conference.title}} <small>{{ 'bibliometry.conference.page_title'|trans }}</small></div>
    {% if is_granted('ROLE_ADMIN') %}
        <div style="margin-top:10px">
            <button class="btn btn-sm btn-danger" data-toggle="modal" data-target="#edit_conference_popup">
                {{ 'bibliometry.conference.edit_conference'|trans }}
            </button>
        </div>
    {% endif %}
{% endblock %}

{% block breadcrumbs %}
    {{ parent() }}
    <li>
        <a href="{{ path('all_conferences_route') }}">{{ 'bibliometry.conferences.page_title'|trans }}</a>
    </li>
    <li class="active">
        {{ 'bibliometry.conference.page_title'|trans }}
    </li>
{% endblock %}

{% block body %}
{# Left part #}
<div class="col-md-8">
    <h2 class="page-header">{{ 'bibliometry.conference.details'|trans }}</h2>
    
    <div class="box box-solid bg-light-blue">
        <div class="box-header">
            <h3 class="box-title">{{ conference.title }}</h3>
        </div>
    </div><!-- /.box-body -->

    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title"><i class="fa fa-list"></i> {{ 'bibliometry.conference.publications'|trans }}</h3>
        </div>
        <div class="box-body">
            {% include "BibliometryMainBundle:Conference:showPublicationsTable.html.twig" with {"publiConferences" : conference.getPubliConferences() } %}
        </div>
    </div>
</div>

{# Right part #}
<div class="col-md-4">
    {# Ranking box #}
    <h2 class="page-header">{{ 'bibliometry.conference.ranking'|trans }}</h2>
    <!-- small box -->
    <div class="small-box bg-{{ conference.getConferenceRankingLabel()|conf_background_color }}">
        <div class="inner">
            <h3>
                {{ conference.getConferenceRankingLabel() }}
            </h3>
            <p>
                {{ conference.getLastConferenceRanking() ? 'from CORE '~conference.getLastConferenceRanking().year : 'bibliometry.conference.no_ranking'|trans }}
            </p>
        </div>
        <div class="icon">
            <i class="ion ion-stats-bars"></i>
        </div>
        {% set conf_link = conference.getCoreLink() %}
        {% if conf_link %}
            <a href="{{ conf_link }}" class="small-box-footer" target="_blank">
                {{ 'bibliometry.conference.more_info'|trans }} <i class="fa fa-arrow-circle-right"></i>
            </a>
        {% else %}
            <a href="#" class="small-box-footer">
                {{ 'bibliometry.conference.no_ranking'|trans }}
            </a>
        {% endif %}
    </div>
    <h2 class="page-header">{{ 'bibliometry.conference.editions'|trans }}</h2>
    {% for publiConference in conference.getEditions() %}
        <div class="small-box bg-blue">
            <div class="inner">
                <h3>
                    {{ publiConference.getYear() }}
                </h3>
                <p>
                    {{ publiConference.city }}<br>
                    {{ ('bibliometry.countries.'~publiConference.country)|trans }}
                </p>
            </div>
            <div class="icon">
                <span class="flag-icon flag-icon-{{ publiConference.country }}" style="font-size:75px"></span>
            </div>
        </div>
    {% endfor %}
</div>

{% if is_granted('ROLE_ADMIN') %}
    {% block edit_conference %}
        {{ render(controller('BibliometryMainBundle:Conference:editConference', { 'slug_conference': conference.slug })) }}
    {% endblock %}
{% endif %}

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {# Scripts for data table #}
    <!-- DATA TABES SCRIPT -->
    <script src="{{ asset('js/plugins/datatables/jquery.dataTables.js') }}" type="text/javascript"></script>
    <script src="{{ asset('js/plugins/datatables/dataTables.bootstrap.js') }}" type="text/javascript"></script>

    <!-- page script -->
    <script type="text/javascript">
        $(function() {
            var oTable = $('.publications_table').dataTable({
                "bPaginate": true,
                "bLengthChange": true,
                "bFilter": true,
                "bSort": true,
                "bInfo": true,
                "bAutoWidth": false,
                "aaSorting": [[ 0, "desc" ]]
            });
        });
    </script>
{% endblock %}

src/Bibliometry/MainBundle/Resources/views/Conference/showConferences.html.twig
{% extends "::base.html.twig" %}

{% block title %}{{ parent() }} - {{ 'bibliometry.conferences.html_title'|trans }}{% endblock %}

{% block page_title %}{{ 'bibliometry.conferences.page_title'|trans }}{% endblock %}

{% block breadcrumbs %}
    {{ parent() }}
    <li class="active">
        {{ 'bibliometry.conferences.page_title'|trans }}
    </li>
{% endblock %}

{% block body %}
    <div class="col-md-12">
        <div class="box box-solid">
            <div class="box-header">
                <h3 class="box-title"><i class="fa fa-list"></i> {{ 'bibliometry.conferences.nb_conferences'|trans({'%nb_conferences%': conferences|length}) }}</h3>
            </div>
            <div class="box-body">
                <div class="box-body table-responsive">
                    <table class="researchers_table table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th></th>
                                <th>{{ 'bibliometry.conferences.acronym'|trans }}&nbsp;&nbsp;&nbsp;</th>
                                <th>{{ 'bibliometry.conferences.title'|trans }}</th>
                                <th>{{ 'bibliometry.conferences.nb_publications'|trans }}</th>
                                <th>{{ 'bibliometry.conferences.ranking'|trans }}&nbsp;&nbsp;&nbsp;</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for conference in conferences %}
                                <tr>
                                    <td><a href="{{ path('conference_route', {'slug_conference': conference.slug}) }}"><button class="btn btn-primary btn-sm"><i class="fa fa-file-text-o"></i> {{ 'bibliometry.conferences.details'|trans }}</button></a></td>
                                    <td align="center"><a href="{{ path('conference_route', {'slug_conference': conference.slug}) }}">{{ conference.acronym }}</a></td>
                                    <td><a href="{{ path('conference_route', {'slug_conference': conference.slug}) }}">{{ conference.title }}</a></td>
                                    <td>{{ conference.getNbPubli }}</td>
                                    {% set confRanking = conference.getLastConferenceRanking() %}
                                    <td align="center" data-order="{{ confRanking ? confRanking.valueInteger : 6 }}">
                                        {% if confRanking %}
                                            {{ confRanking.value|conf_color|raw }}
                                        {% else %}
                                            {% if conference.getConferenceRankingLabel() == "FR" %}
                                                <span class="flag-icon flag-icon-fr" style="font-size:20px"></span>
                                            {% else %}
                                                -
                                            {% endif %}
                                        {% endif %}
                                    </td>   
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div><!-- /.box-body -->
            </div><!-- /.box-body -->
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {# Scripts for data table #}
    <!-- DATA TABES SCRIPT -->
    <script src="{{ asset('js/plugins/datatables/jquery.dataTables.js') }}" type="text/javascript"></script>
    <script src="{{ asset('js/plugins/datatables/dataTables.bootstrap.js') }}" type="text/javascript"></script>
    
    <script type="text/javascript">
        $(function() {
            var oTable = $('.researchers_table').dataTable({
                "bPaginate": true,
                "bLengthChange": true,
                "iDisplayLength": 50,
                "bFilter": true,
                "bSort": true,
                "bInfo": true,
                "bAutoWidth": false,
                "aaSorting": [[ 3, "desc" ]]
            });
        });
    </script>
{% endblock %}

src/Bibliometry/MainBundle/Resources/views/Conference/showPublicationsTable.html.twig
<div class="box-body table-responsive">
    <table class="publications_table table table-bordered table-striped">
        <thead>
            <tr>
                <th>{{ 'bibliometry.conference.year'|trans }}&nbsp;&nbsp;&nbsp;</th>
                <th>{{ 'bibliometry.conference.title'|trans }}</th>
                <th>{{ 'bibliometry.conference.authors'|trans }}</th>
            </tr>
        </thead>
        <tbody>
            {% for publiConference in publiConferences %}
                {% set publication = publiConference.publication %}
                {% if publication != null %}
                    <tr>
                        <td align="center">{{ publication.year }}</td>
                        <td><a href="{{ path('publication_route', {'slug_publication':publication.slug}) }}">#{{ publication.id }} {{ publication.title }}</a></td>
                        <td>
                            {% for author in publication.authors %}
                                {% if hasRightToSee %}
                                    <a href="{{ path('researchers_researcher_researcher', {'slug_researcher': author.slug}) }}">{{ author.name }} {{ author.surname }}</a>{% if not loop.last %}, {% endif %}
                                {% else %}
                                    {{ author.name }} {{ author.surname }}{% if not loop.last %}, {% endif %}
                                {% endif %}
                            {% endfor %}
                        </td>
                    </tr>
                {% endif %}
            {% endfor %}
        </tbody>
    </table>
</div><!-- /.box-body -->